### ISSUE TITLE
在 Safari 瀏覽器中 分頁無法切換

### ISSUE THREAD

**Issue by t510599** [stoneapptech/webeditor#7]

**Comment by t510599** [comment]
![imag0677](https://user-images.githubusercontent.com/18533304/34978434-3089df44-fad9-11e7-9c51-14d369a88c8a.jpg)

**Comment by t510599** [comment]
@t510599

**Comment by secminhr** [comment]
Fixed in the pull request.

**Comment by t510599** [comment]
Closed by https://github.com/stoneapptech/webeditor/commit/df3edf5363f526ec459b3112a3d30d7766952274 .
